# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20190125_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cates',
            options={'permissions': (('show_cates', '查看类别管理'), ('insert_cates', '添加类别'), ('edit_cates', '修改类别'), ('del_cates', '删除类别'))},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('show_goods', '查看商品管理'), ('insert_goods', '添加商品'), ('edit_goods', '修改商品'), ('del_goods', '删除商品'))},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('show_order', '查看订单管理'), ('insert_order', '添加订单'), ('edit_order', '修改订单'), ('del_order', '删除订单'))},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('show_users', '查看会员管理'), ('insert_users', '添加会员'), ('edit_users', '修改会员'), ('del_users', '删除会员'))},
        ),
    ]
